#ifndef __constants__
#define	__constants__

  #define FALSE 0
  #define TRUE 1

  /* ESSAS CONSTANTES PRECISAM VIRAR VARIAVEIS GLOBAIS */
  /* LIDAS DO BLOCO DE BOOT */
  #define SECTOR_PER_BLOCK 4
  #define BLOCK_SIZE SECTOR_PER_BLOCK * SECTOR_SIZE

  #define DISK_SECTORS 32768
  #define DISK_BLOCKS DISK_SECTORS / SECTOR_PER_BLOCK

  /* Partições do disco */
  #define BOOT_BLOCK_SIZE 1
  #define BOOT_SECTOR_SIZE BOOT_BLOCK_SIZE * SECTOR_PER_BLOCK

  #define MFT_BLOCK_SIZE 2048
  #define MFT_SECTOR_SIZE MFT_BLOCK_SIZE * SECTOR_PER_BLOCK

  #define DATA_BLOCK_SIZE (DISK_SECTORS - (BOOT_SECTOR_SIZE + MFT_SECTOR_SIZE))
  #define DATA_SECTOR_SIZE DATA_BLOCK_SIZE / SECTOR_PER_BLOCK

  /* Disco */
  #define SECTOR_SIZE 256

  #define BOOT_BLOCK 0
  #define MFT_BLOCK 1
  #define DATA_BLOCK MFT_BLOCK_SIZE + 1

#endif
