#ifndef __constants__
#define	__constants__

  #define FALSE 0
  #define TRUE 1

  /* Disco */
  #define SECTOR_SIZE 256
  #define SECTOR_PER_BLOCK 4
  #define BLOCK_SIZE SECTOR_PER_BLOCK * SECTOR_SIZE

  #define DISK_SECTORS 32768
  #define DISK_BLOCKS DISK_SECTORS / SECTOR_PER_BLOCK

  #define BOOT_BLOCK_SIZE 1
  #define BOOT_SECTOR_SIZE BOOT_BLOCK_SIZE * SECTOR_PER_BLOCK

  #define MFT_BLOCK_SIZE 2048
  #define MFT_SECTOR_SIZE MFT_BLOCK_SIZE * SECTOR_PER_BLOCK

  #define DATA_BLOCK_SIZE DISK_BLOCKS - (BOOT_BLOCK_SIZE + MFT_BLOCK_SIZE)
  #define DATA_SECTOR_SIZE DISK_SECTORS - (BOOT_SECTOR_SIZE + MFT_SECTOR_SIZE)

  #define BOOT_BLOCK 0
  #define MFT_BLOCK BOOT_BLOCK + 1
  #define DATA_BLOCK MFT_BLOCK_SIZE + 1

  #define BOOT_SECTOR 0
  #define MFT_SECTOR BOOT_SECTOR + SECTOR_PER_BLOCK
  #define DATA_SECTOR MFT_SECTOR_SIZE + SECTOR_PER_BLOCK

  /* Tuplas */
  #define MAX_TUPLAS_REGISTER 32
  #define TUPLA_SIZE REGISTER_SIZE / MAX_TUPLAS_REGISTER

  /* Registro */
  #define REGISTER_SIZE 512
  #define REGISTER_PER_BLOCK BLOCK_SIZE / REGISTER_SIZE
  #define MAX_REGISTERS MFT_SECTOR_SIZE / REGISTER_PER_BLOCK

  #define REGISTER_BOOT_BLOCK 0
  #define REGISTER_ROOT 1

  #define REGISTER_FIM 0
  #define REGISTER_MAP 1
  #define REGISTER_ADITIONAL 2
  #define REGISTER_FREE -1

  /* Record */
  #define RECORD_SIZE 64
  #define RECORD_TYPE 0
  #define RECORD_NAME 1
  #define RECORD_BLOCK_FILE_SIZE 52
  #define RECORD_BYTES_FILE_SIZE 56
  #define RECORD_MFT_NUMBER 60

  /* Arquivo */
  #define FILENAME_SIZE_LIMIT 51

#endif
